version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rac
      POSTGRES_PASSWORD: demotest
      POSTGRES_DB: backenddb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rac:demotest@db:5432/backenddb
